---
- name: Deploy Web App
  hosts: n2
  become: yes

  tasks:
    - name: Install Git 
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Host Code
      git:
        repo: https://github.com/CeeyIT-Solutions/food3.git
        dest: /var/www/html
...
